### ISSUE TITLE
 Write data loader for potree

### ISSUE THREAD

**Issue by calistenson** [NextDroid/potree#47]
Create a data loader based on the VisualizationPrimitives api and the flatbuffer of REM assessment data to visualize spheres of the control points on a lane. 

Stretch: visualize the REM estimate of where the car appears in the world frame. (idea: have a faded car mesh appear in this position).

**Comment by calistenson** [comment]
Visualize:

control points (rt) as blue dots on lane. (load in from flatbuffer)
---- note on serializing the data with assessment tools need to convert this from relative car frame into world frame. Take rt position as a reference point and then converting the points accordingly into the world frame outwriting to flatbuffer.
Secondary visualization: REM/aptiv estimate of where car is world frame throughout drive (represent as x's? other color dots?).
Use a callback to load in each mesh:

https://github.com/NextDroid/potree/blob/develop/demo/radar.html#L728

**Comment by calistenson** [comment]
https://github.com/NextDroid/DataSchemas/blob/develop/schemas/VisualizationPrimitives.fbs

**Comment by vrajur-nd** [comment]
Update 2019-09-13: 

Added a small fix so that the timestamps work for hiding/showing the control points

![REM-Control-Points-Potree.png](https://images.zenhubusercontent.com/5aa183ef4b5806bc2bca0c77/53e318ad-82ae-4cf8-8c22-792f4896830b)

We still have that issue with the amount of data that needs to be loaded

**Comment by vrajur-nd** [comment]
Complete.
