### ISSUE TITLE
Bug in scripts/convert-lanes-json-to-flatbuffer.py

### ISSUE THREAD

**Issue by arjunskND** [NextDroid/potree#82]
After re-annotating lanes for a LG dataset (TDP_064_2019-06-26T17-35-23_Vel_80_60_Acc_min_Dir_left_Logging), such that the right lane is more sparse, this script crashes in the create spine method. If the lanes are annotated after running the down sample script in LidarPerception, the imbalance is far less severe and the script runs just fine. What is the reason for the crash and is there simple fix?

**Comment by vrajur-nd** [comment]
@jallen-NextDroid we can close this issue right?

**Comment by arjunskND** [comment]
@vrajur-nd, you said the bug was due to duplicate points at the same location and that lidar perception was righting them. Given we know that, this issue can be closed. I guess, one may need to be open for those duplicate points in lidar perception. Down sample also removes this issue though

**Comment by arjunskND** [comment]
I still haven't formalized action items from Veritas#76, but that sort of talks about this and alike and lists action items there as well

**Comment by vrajur-nd** [comment]
Yeah, the issue was LidarPerception putting down a lot duplicate points on one of the lanes at the very beginning. Downsample script does address that issue, and additionally, James' PR addressed the script crashing in this scenario. I think having Veritas#76 as a follow up is enough to close this issue. Thoughts?
