### ISSUE TITLE
POTree hangs a few seconds after load -- recovers a minute later

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/potree#91]
After POTree loads the point cloud and the user can interact for a few seconds, POTree freezes.  Chrome eventually throws up a "Page Unresponsive" warning.  If you click "Wait" it eventually recovers, without any future issues.

Unknown if this is an issue on machines other than mine.

**Comment by vrajur-nd** [comment]
Looks like this is due to the `loadTracks()` function. The representation of track bounding boxes is not very space efficient since a separate box mesh is created for each track at each of its poses (i.e. a single track that has 10 poses will be made of 10 meshes). The hanging issue specifically seems to be from the number of track objects that need to be created.

There are a couple things that can be done to address the issue either partially or completely:
 - Put the track loader in a separate thread so that the visualization does not freeze while the tracks are being loaded.
 - Redo the way that tracks are represented, so that only a single mesh is created for each track and its position and visibility is updated based on the animation time (reduce the overall memory footprint)
 - Implementing some way of streaming flatbuffer data would probably be the truly scalable solution

**Comment by vrajur-nd** [comment]
Update 2019-12-04:

There is a branch pushed `feature/updated-loading-progress` to potree that displays a loading screen with a status message based on what's being loaded. It is fairly hacky and the loading messages do not always indicate correctly what exactly is being loaded, but it does help convey that things are being loaded and so the visualization is lagging during that process...

**Comment by vrajur-nd** [comment]
Reassigning to Arjun

**Comment by dgandhiAM** [comment]
@bcasselsND will look into this with @Jakobeha-nextdroid
